# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db5904e12fe724bfd45822bc26850935d918e2999f52bb0d43efe09c08438a2a8795207e5d82f5e553e099c65061d31e40dfcc5891e0174fe2c3859299e3ee32

test:
  secret_key_base: ab145ae7bdae9a7fe1cdd247e4a2a754ad3176da874c214f7277d3806d98fbf05c542421ca4a614b077f621dab8f109af2d0509c9ae4947dd4926390e405752a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f13d3d8a5345b340db302049319982ca7048b12b0b265dbd6a251fb6f2d00be1bdca18c197b8593684e225a0d24842e77f95641e10ba127e4e267f4156f9e38f
# secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
